version: '3'
services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - images:/app/images
  # ngrok:
  #   build:
  #     context: ./ngrok
  #   depends_on:
  #     - proxy
volumes:
  images:
